### ISSUE TITLE
No error in the UI when connecting to a database with no network

### ISSUE THREAD

**Issue by aferrandi** [aferrandi/dbtarzan#101]
[ERROR] [01/06/2020 08:02:58.970] [Sys-my-pinned-dispatcher-9] [akka://Sys/user/configWorker/$a] The connection to the host sql-test02, named instance gtest failed. Error: "java.net.UnknownHostException: sql-test02.". Verify the server and instance names and check that no firewall is blocking UDP traffic to port 1434.  For SQL Server 2005 or later, verify that the SQL Server Browser Service is running on the host.
akka.actor.ActorInitializationException: akka://Sys/user/configWorker/$a/$a: exception during creation
	at akka.actor.ActorInitializationException$.apply(Actor.scala:195)
	at akka.actor.ActorCell.create(ActorCell.scala:657)
	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:509)
	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:531)
	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:294)
	at akka.dispatch.Mailbox.run(Mailbox.scala:229)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at akka.util.Reflect$.instantiate(Reflect.scala:69)
	at akka.actor.ArgsReflectConstructor.produce(IndirectActorProducer.scala:100)
	at akka.actor.Props.newActor(Props.scala:226)
	at akka.actor.ActorCell.newActor(ActorCell.scala:609)
	at akka.actor.ActorCell.create(ActorCell.scala:635)
	... 7 more
Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: The connection to the host sql-test02, named instance gtest failed. Error: "java.net.UnknownHostException: sql-test02". Verify the server and instance names and check that no firewall is blocking UDP traffic to port 1434.  For SQL Server 2005 or later, verify that the SQL Server Browser Service is running on the host.
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDriverError(SQLServerException.java:234)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.getInstancePort(SQLServerConnection.java:5963)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.primaryPermissionCheck(SQLServerConnection.java:2383)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.login(SQLServerConnection.java:2126)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectInternal(SQLServerConnection.java:1993)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connect(SQLServerConnection.java:1164)
	at com.microsoft.sqlserver.jdbc.SQLServerDriver.connect(SQLServerDriver.java:760)
	at dbtarzan.db.DriverShim.connect(DriverShim.scala:9)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at dbtarzan.db.DriverManagerWithEncryption.getConnection(DriverManagerWithEncryption.scala:11)
	at dbtarzan.db.actor.DatabaseWorker.buildCore(DatabaseWorker.scala:41)
	at dbtarzan.db.actor.DatabaseWorker.<init>(DatabaseWorker.scala:32)

**Comment by aferrandi** [comment]
It was an error in an alpha version of  1.21, provoked by the fact that the exception was not handled by the actor and just displayed in the shell (if it was started by the shell).
Now is the exception caught and sent to the UI.
