### ISSUE TITLE
No message when getting an error from SQLServer

### ISSUE THREAD

**Issue by aferrandi** [aferrandi/dbtarzan#39]
Querying the database HATRMSQL01-D01 got:Building the dbWorker with the driver com.microsoft.sqlserver.jdbc.SQLServerDriver got: at:
dbtarzan.db.ConnectionBuilder.buildDBWorker(ConnectionBuilder.scala:20)
dbtarzan.db.ConnectionBuilder$.buildDBWorker(ConnectionBuilder.scala:49)
dbtarzan.config.actor.ConfigWorker.getDBWorker(ConfigWorker.scala:19)
dbtarzan.config.actor.ConfigWorker.dbtarzan$config$actor$ConfigWorker$$queryDatabase(ConfigWorker.scala:36)
dbtarzan.config.actor.ConfigWorker$$anonfun$receive$1.applyOrElse(ConfigWorker.scala:62)
akka.actor.Actor$class.aroundReceive(Actor.scala:465)
dbtarzan.config.actor.ConfigWorker.aroundReceive(ConfigWorker.scala:12)
akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
akka.actor.ActorCell.invoke(ActorCell.scala:487)
akka.dispatch.Mailbox.processMailbox(Mailbox.scala:254)
akka.dispatch.Mailbox.run(Mailbox.scala:221)
java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
java.lang.Thread.run(Unknown Source)

**Comment by aferrandi** [comment]
Got a better error now. Still, not so much details:

akka.actor.ActorInitializationException: akka://Sys/user/configWorker/$b/$a: exception during creation
        at akka.actor.ActorInitializationException$.apply(Actor.scala:193)
        at akka.actor.ActorCell.create(ActorCell.scala:671)
        at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:525)
        at akka.actor.ActorCell.systemInvoke(ActorCell.scala:547)
        at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:282)
        at akka.dispatch.Mailbox.run(Mailbox.scala:223)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
        at java.lang.reflect.Constructor.newInstance(Unknown Source)
        at akka.util.Reflect$.instantiate(Reflect.scala:65)
        at akka.actor.ArgsReflectConstructor.produce(IndirectActorProducer.scala:96)
        at akka.actor.Props.newActor(Props.scala:213)
        at akka.actor.ActorCell.newActor(ActorCell.scala:626)
        at akka.actor.ActorCell.create(ActorCell.scala:652)
        ... 7 more
Caused by: java.lang.NullPointerException
        at dbtarzan.db.actor.DatabaseWorker.buildCore(DatabaseWorker.scala:30)
        at dbtarzan.db.actor.DatabaseWorker.<init>(DatabaseWorker.scala:21)
        ... 16 more

**Comment by aferrandi** [comment]
The SQL error are now displayed with message, status and error number
