### ISSUE TITLE
A error upon executing dbTarzan on Ubuntu 18.04

### ISSUE THREAD

**Issue by roman-yakimkin** [aferrandi/dbtarzan#72]
Hello.
I'm trying to run dbTarzan on Ubuntu 18.04, but the following error is displayed (on the terminal)

libGL error: unable to load driver: swrast_dri.so
libGL error: failed to load driver: swrast
Prism ES2 Error - nInitialize: glXChooseFBConfig failed
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x0000000000001810, pid=22120, tid=0x00007f15e943c700
#
# JRE version: OpenJDK Runtime Environment (8.0_181-b13) (build 1.8.0_181-8u181-b13-0ubuntu0.18.04.1-b13)
# Java VM: OpenJDK 64-Bit Server VM (25.181-b13 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  0x0000000000001810
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /home/roman/hs_err_pid22120.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
#
 
Could you clarify me, what is the problem and how can I solve it?

**Comment by aferrandi** [comment]
Hi,
How did you install dbtarzan? As a snap, as a debian package or directly as a jar file?

Also, I see around in the internet problems similar to yours. It looks like it could be a problem with the graphical drivers. Which gaphic card do you use? Is it an NVidia?

**Comment by roman-yakimkin** [comment]
Yes, I tried to install it as a snap and as a Debian package. 
And yes, I have an NVidia graphics card.
I also saw a lot of similar discussions on the Internet but I couldn't solve it.

**Comment by aferrandi** [comment]
I don't have the possibility to see exactly what is the status of your installation, but for the comments I see online I can tell the following:

dbtarzan is based on JavaFX, which is based on Prism (https://docs.oracle.com/javafx/2/architecture/jfxpub-architecture.htm). Prism uses OpenGL (glXChooseFBConfig) and this seems to cause the problem.
On the other side there seem to be some potential issues with snaps and NVidia drivers in some cases, which include swrast_dri.so: for example https://forum.shotcut.org/t/new-17-11-snapd-version-doesnt-launch/3105 and https://forum.snapcraft.io/search?q=swrast_dri.so, but searching using the words "snap and swrast_dri.so" you find more.
Actually the dbtarzan snap includes the swrast_dri.so library, as  /usr/lib/x86_64-linux-gnu/dri/swrast_dri.so.

So, it almost seems that for some reason it does not find the correct library.
If I was you I would try to :
1) run dbtarzan as jar file (see in https://aferrandi.github.io/dbtarzan/Installation.html how to install it). To do this you need to have both Java and JavaFX installed, which should be true since you run the .deb file.
2) install another snap that uses opengl and see if it gives the same error (e.g. https://snapcraft.io/openra).

By the way, did you get the same error running the .deb package and the snap?

**Comment by aferrandi** [comment]
In the meantime I can see if it is possible to create a snap which is compatible with more graphical environments.

**Comment by aferrandi** [comment]
@roman-yakimkin  could you please check what happens if you run directly the jar (https://github.com/aferrandi/dbtarzan/releases/download/1.16/dbtarzan-assembly-1.16.jar) in the following way?

`java -jar dbtarzan-assembly-1.16.jar`

Do you get an error? The same error?

**Comment by roman-yakimkin** [comment]
Hello.
I did it and saw the error message.

Graphics Device initialization failed for :  es2, sw
Error initializing QuantumRenderer: no suitable pipeline found
java.lang.RuntimeException: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
	at com.sun.javafx.tk.quantum.QuantumRenderer.getInstance(QuantumRenderer.java:280)
	at com.sun.javafx.tk.quantum.QuantumToolkit.init(QuantumToolkit.java:221)
	at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:248)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:209)
	at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:675)
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:695)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$1(LauncherImpl.java:182)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(QuantumRenderer.java:94)
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:124)
	... 1 more
Exception in thread "main" java.lang.RuntimeException: No toolkit found
	at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:260)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:209)
	at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:675)
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:695)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$1(LauncherImpl.java:182)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by aferrandi** [comment]
The system uses OpenJDK 11 now, so this should not be an issue anymore
